import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import 'katex/dist/katex.min.css';
import './globals.css';
import { handleGetUserInfo } from '@/server/actions/user';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'VoltEdge Electronics Rag',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = await fetch("http://localhost:3001/api/ensure-id", {
    cache: "no-store",
  });
  
  const { userId } = await res.json(); 
  const userInfo = await handleGetUserInfo(userId);


  return (
    <html data-user-id={JSON.stringify(userInfo)} lang="en" className={`${userInfo.preferences.theme} overflow-hidden h-full`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full bg-light-bg dark:bg-dark-bg`}
      >
        {children}
      </body>
    </html>
  );
}
